export const BR_STATES = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
] as const;

export const INTEREST_TYPE_OPTIONS = [
  { value: 'food_service', label: 'Food Service' },
  { value: 'b2b', label: 'B2B (Indústrias, redes e atacadistas)' },
  { value: 'terceirizacao', label: 'Terceirização de Produção' },
  { value: 'envase', label: 'Envase' },
  { value: 'marcas_proprias', label: 'Marcas Próprias' },
  { value: 'distribuicao', label: 'Distribuição' },
  { value: 'representante', label: 'Representante' },
] as const;

export const OPERATION_TYPE_OPTIONS = [
  { value: 'restaurante', label: 'Restaurante' },
  { value: 'cozinha_industrial', label: 'Cozinha industrial' },
  { value: 'rede_food_service', label: 'Rede de food service' },
  { value: 'padaria', label: 'Padaria / Confeitaria' },
  { value: 'hotel', label: 'Hotelaria' },
  { value: 'outro', label: 'Outro' },
] as const;
